name: clover

services:
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ROOT_USER: rustfsadmin
      RUSTFS_ROOT_PASSWORD: rustfsadmin
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  rustfs_data:
  rustfs_logs:
